spring:
  config:
    activate:
      on-profile: prod
    import:
      - security/application-api.yml
      - security/application-database.yml
      - security/application-security.yml
  jpa:
    open-in-view: true