spring:
  config:
    activate:
      on-profile: test
    import:
      - security/application-api.yml
      - security/application-security.yml
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      host: localhost
      port: 6379