spring:
  config:
    activate:
      on-profile: test
    import:
      - security/application-api.yml
      - security/application-security.yml

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1; # test 부분을 자신이 원하는 것으로 바꾸시면 됩니다.
    username: sa # username과 password는 자신의 설정에 맞게
    password:
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      host: localhost
      port: 6379

schedules:
  cron:
    reward:
      publish: 0 00 01 * * ?

seouldata:
  tbLnOpendataRentV:
    key: 6c6979506c726b64363262454c6d61

SHINHAN_BANK:
  API:
    KEY: 2023_Shinhan_SSAFY_Hackathon
    URL: https://shbhack.shinhan.com
    URI:
      1TRANSFER: /v1/auth/1transfer
      SEARCH_NAME: /v1/search/name

kakao:
  API:
    URL: 288f33db797d9620f65fe61ce41fa2a4